---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == 'RedHat' or
      ansible_os_family == 'Debian'

- name: Create YUM repo file
  yum_repository:
    name: glusterfs
    description: GlusterFS YUM repo
    baseurl: "{{ glusterfs_server_yumrepo_url }}"
    gpgcheck: no
  when: >
    ansible_os_family == 'RedHat'
  tags:
    - glusterfs_server_pkg

- name: Add APT repo key
  apt_key:
    url: "{{ glusterfs_server_apt_key }}"
  when: >
    glusterfs_server_apt_key | length > 0 and
    ansible_os_family == 'Debian' and
    ansible_distribution == 'Debian'
  tags:
    - glusterfs_server_pkg

- name: Create APT repo file
  apt_repository:
    repo: "{{ glusterfs_server_apt_url }}"
  when: >
    ansible_os_family == 'Debian'
  tags:
    - glusterfs_server_pkg

- name: Install GlusterFS server
  package:
    name: "{{ glusterfs_server_pkg }}"
  notify:
    - Restart GlusterFS service
  tags:
    - glusterfs_server_pkg

- name: Enable the GlusterFS service
  service:
    name: "{{ glusterfs_server_service }}"
    enabled: yes
  tags:
    - glusterfs_server_service

- name: Run the GlusterFS service
  service:
    name: "{{ glusterfs_server_service }}"
    state: started
  register: glusterfs_server_service_started
  tags:
    - glusterfs_server_service

- include_tasks: volume.yaml
  loop: "{{ glusterfs_server_volumes }}"
  loop_control:
    loop_var: vol
  tags:
    - glusterfs_server_volume
